#!/bin/bash
# Quick Commands Reference for Monopoly Backend Deployment

echo "=================================="
echo "Monopoly Backend - Quick Commands"
echo "=================================="
echo ""
echo "🚀 DEPLOYMENT"
echo "  ./deploy.sh                    # Deploy/redeploy aplikasi"
echo ""
echo "📊 MONITORING"
echo "  docker-compose ps              # Status containers"
echo "  docker-compose logs -f         # Follow logs real-time"
echo "  docker-compose logs --tail=50  # Last 50 log lines"
echo "  docker stats                   # Resource usage"
echo ""
echo "🔧 MANAGEMENT"
echo "  docker-compose start           # Start containers"
echo "  docker-compose stop            # Stop containers"
echo "  docker-compose restart         # Restart containers"
echo "  docker-compose down            # Stop and remove containers"
echo ""
echo "🔄 UPDATE"
echo "  docker-compose build           # Rebuild image"
echo "  docker-compose up -d           # Start in background"
echo "  docker-compose build --no-cache # Force rebuild"
echo ""
echo "🧹 CLEANUP"
echo "  docker system prune -a         # Clean unused resources"
echo "  docker-compose down -v         # Remove volumes"
echo ""
echo "🔍 TESTING"
echo "  curl http://localhost:8080/health"
echo "  curl http://13.212.217.150:8080/health"
echo ""
echo "🌐 URLs"
echo "  API:     http://13.212.217.150:8080"
echo "  Swagger: http://13.212.217.150:8080/swagger"
echo "  Health:  http://13.212.217.150:8080/health"
echo ""
